USE `itunes1`;

DROP FUNCTION IF EXISTS GetAveragePrice;
DELIMITER //
CREATE FUNCTION GetAveragePrice()
    RETURNS DECIMAL(8, 2)
    DETERMINISTIC
BEGIN
RETURN (SELECT AVG(price) FROM `download`);
END //
DELIMITER ;