USE `itunes1`;

DROP FUNCTION IF EXISTS GetAveragePrice;
DELIMITER //
CREATE FUNCTION GetAveragePrice()
    RETURNS DECIMAL(8, 4)
    DETERMINISTIC
BEGIN
RETURN (SELECT AVG(quantity) FROM `download`);
END //
DELIMITER ;